### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Kyson/WhorlView#1]
I get this:

![image](https://user-images.githubusercontent.com/5357526/37156517-f3525cf8-22ee-11e8-95f4-4197b0deea7d.png)

**Comment by Kyson** [comment]
@AndroidDeveloperLB Pls make sure u got a right java environment, try this command line 'java -version'

**Comment by AndroidDeveloperLB** [comment]
I already have the right java env. I can open other projects and create new ones just fine, including building and running of course.

Now I get this instead:


![image](https://user-images.githubusercontent.com/5357526/61652825-86199580-acc1-11e9-98d3-d281c2b4d3d9.png)


So when I try to make the second line a comment:

```
//apply plugin: 'com.github.dcendents.android-maven'
```

I get this :

![image](https://user-images.githubusercontent.com/5357526/61652894-afd2bc80-acc1-11e9-8f09-e0d4f93f4fb9.png)

And then, if I make the entire "install" part a comment, update some stuff, remove the build-tools, etc...

Then it all worked.

Please fix these issues.
